version: '3.7'

services:
  db:
    image: mariadb
    container_name: matomo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: matomo_password
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo_user
      MYSQL_PASSWORD: matomo_password
    volumes:
      - db_data:/var/lib/mysql

  matomo:
    image: matomo
    container_name: matomo-app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo_user
      MATOMO_DATABASE_PASSWORD: matomo_password
      MATOMO_DATABASE_DBNAME: matomo
    volumes:
      - matomo_data:/var/www/html

volumes:
  db_data:
  matomo_data:
